/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import model.DBConnection;
import view.MainFrame;
import view.ResultFrame;

/**
 *
 * @author amiel
 */
public class LeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeftPanel
     */
    private MainFrame mf;
    private DBConnection dbc;
    public LeftPanel(MainFrame mf) {
        this.mf = mf;
        initComponents();
        checkIfAdmin();
    }
    public void checkIfAdmin(){
        dbc = new DBConnection();
        dbc.getConnection();
        ResultSet rs = dbc.executeQuery("SELECT * FROM admins WHERE adminID = '" + mf.getMainFrame_Listener().getAccount().getUserId() + "'");
        boolean visible = false;
        try{
            if(rs.next()){
                visible = true;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        adminBtn.setVisible(visible);
    }
    public void resetButtons(){
        categoryBtn.setSelected(false);
        companiesBtn.setSelected(false);
    }

    public JToggleButton getCategoryBtn() {
        return categoryBtn;
    }

    public JToggleButton getCompaniesBtn() {
        return companiesBtn;
    }

    public JButton getSearchBtn() {
        return searchBtn;
    }

    public JTextField getSearchField() {
        return searchField;
    }

    public JButton getAdminBtn() {
        return adminBtn;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        categoryBtn = new javax.swing.JToggleButton();
        companiesBtn = new javax.swing.JToggleButton();
        searchPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setMaximumSize(new java.awt.Dimension(200, 500));
        setMinimumSize(new java.awt.Dimension(200, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 500));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200x100.png"))); // NOI18N

        categoryBtn.setBackground(new java.awt.Color(255, 255, 255));
        categoryBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        categoryBtn.setText("Categories");
        categoryBtn.setSize(200,100);
        categoryBtn.setMinimumSize(new java.awt.Dimension(200, 100));

        companiesBtn.setBackground(new java.awt.Color(255, 255, 255));
        companiesBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        companiesBtn.setText("Companies");
        companiesBtn.setSize(200,100);

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        searchBtn.setText("Search");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addGap(62, 62, 62))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        adminBtn.setText("Profit View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companiesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(adminBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JToggleButton categoryBtn;
    private javax.swing.JToggleButton companiesBtn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables
}
