/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.center_panels;

import java.sql.*;
import javax.swing.JOptionPane;
import model.DBConnection;
import panel_control.CenterPanel_Listener;

/**
 *
 * @author amiel
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPanel
     */
    private DBConnection dbc;
    private CenterPanel_Listener cpl;
    private int accId;
    public SettingsPanel(CenterPanel_Listener cpl) {
        dbc = new DBConnection();
        dbc.getConnection();
        this.cpl = cpl;
        accId = cpl.getMfl().getAccount().getUserId();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settingsLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        passwordBtn = new javax.swing.JButton();
        contactBtn = new javax.swing.JButton();
        emailBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        settingsLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        settingsLabel.setText("Settings");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(settingsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingsLabel)
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        passwordBtn.setText("Change Password");
        passwordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBtnActionPerformed(evt);
            }
        });

        contactBtn.setText("Change Contact No");
        contactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBtnActionPerformed(evt);
            }
        });

        emailBtn.setText("Change email");
        emailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(passwordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(contactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(emailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void updateQuery(String col, String val){
        String checkQuery = "SELECT * FROM account WHERE " + col + " = '" + val + "'";
        String query = "UPDATE account SET " + col + " = '" + val + "' WHERE accountID = '" +  accId + "'";
        try{
            boolean newExist = false;
            ResultSet rs1 = dbc.executeQuery(checkQuery);
            if(rs1.next()){
                newExist = true;
            }
            if(!newExist){
                dbc.updateQuery(query);
                JOptionPane.showMessageDialog(null, col + " changed successfully!");
                if(col.compareToIgnoreCase("email") == 0){
                    cpl.getMfl().getAccount().setEmail(val);
                    cpl.getMfl().getMainFrame().getCenterPanel().getProfilePanel().refresh();
                }else{
                    cpl.getMfl().getAccount().setContactNo(val);
                    cpl.getMfl().getMainFrame().getCenterPanel().getProfilePanel().refresh();
                }
            }else{
                JOptionPane.showMessageDialog(null, col + " is already in use!");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    private void emailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBtnActionPerformed
        String newMail = JOptionPane.showInputDialog("New Email:");
        try{
            if(newMail.length() == 0 || newMail == null){
                JOptionPane.showMessageDialog(null,"Please enter a value");
            }else
                updateQuery("email", newMail);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter a value");
        }
        
    }//GEN-LAST:event_emailBtnActionPerformed

    private void contactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBtnActionPerformed
        String newNum = JOptionPane.showInputDialog("New Contact number:");
        try{
            if(newNum.length() == 0){
                JOptionPane.showMessageDialog(null,"Please enter a value");
            }else
                updateQuery("contactNo", newNum);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter a value");
        }
    }//GEN-LAST:event_contactBtnActionPerformed

    private void passwordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBtnActionPerformed
        String newPass = JOptionPane.showInputDialog("New Password:");
        String query = "UPDATE account SET password = '" + newPass + "' WHERE accountId = '" + accId + "'";
        try{
            if(newPass.length() == 0 || newPass == null){
                JOptionPane.showMessageDialog(null,"Please enter a value");
            }else{
                try{
                    dbc.updateQuery(query);
                    JOptionPane.showMessageDialog(null,"password changed successfully!");
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter a value");
        }
        
        
        
    }//GEN-LAST:event_passwordBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contactBtn;
    private javax.swing.JButton emailBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton passwordBtn;
    private javax.swing.JLabel settingsLabel;
    // End of variables declaration//GEN-END:variables
}
