/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.DBConnection;
import panel_control.CenterPanel_Listener;

/**
 *
 * @author amiel
 */
public class checkoutFrame extends javax.swing.JFrame {
    private CenterPanel_Listener cpl;
    /**
     * Creates new form checkoutFrame
     */
    private DBConnection dbc;
    public checkoutFrame(CenterPanel_Listener cpl) {
        this.cpl = cpl;
        dbc = new DBConnection();
        dbc.getConnection();
        initComponents();
        addContents();
        setVisible(true);
    }
    private void addContents(){
        String[] str = cpl.getShipping();
        for(int i = 0 ; i < str.length ; i ++){
            shipMethodBox.addItem(str[i]);
        }
        
        String[] str2 = cpl.getAddress();
        for(int i = 0 ; i < str2.length ; i++){
            shipAddressbox.addItem(str2[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        shipAddressbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        shipMethodBox = new javax.swing.JComboBox<>();
        proceedBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Select Shipping Address");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("Select Payment Method");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paypal", "AliPay", "Visa", "MasterCard", "Paysafe Card" }));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Select Shipping Method");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        proceedBtn.setText("Proceed");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });

        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shipAddressbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(shipMethodBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipAddressbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shipMethodBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedBtn)
                    .addComponent(returnBtn))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        // TODO add your handling code here:
        String option = (String)shipAddressbox.getSelectedItem();
        System.out.println("checkout btn pressed!");
        if(option.compareToIgnoreCase("Add a shipping address in profile first!") == 0 ){
            JOptionPane.showMessageDialog(null, "Add an address first!");
        }else{
            double total = 0;
            String[] cart = cpl.getMfl().getMainFrame().getCenterPanel().getCartPanel().getCart();
            String shipName = (String)shipMethodBox.getSelectedItem();
            shipName = shipName.split(" \\| ")[0];
            for(int i = 0 ; i < cart.length ; i ++){
                String split = cart[i].split(" \\| ")[2];
                total += Double.parseDouble(split.replace('P', ' '));
            }
            int orderID = 0;
            String queryTransfer = "INSERT INTO `order` (userID, totalAmt, orderStatus, orderDate, shippingID, shipAddress) VALUES ('"+ cpl.getMfl().getAccount().getUserId() + "', '"+ total +"', 'Processing', CURDATE(), (SELECT shippingId FROM shipping WHERE shippingName = '" + shipName + "'), '" + option +"')";
            String getOrderId = "SELECT MAX(orderID) FROM `order` WHERE userID = '" + cpl.getMfl().getAccount().getUserId() + "'";
            String getCart = "SELECT * FROM cart c, accountcart ac WHERE c.cartID = ac.cartID AND ac.accountID = '" + cpl.getMfl().getAccount().getUserId() + "'";
            dbc.updateQuery(queryTransfer);
            ResultSet transfer;
            try{
                transfer = dbc.executeQuery(getOrderId);
                transfer.next();
                orderID = transfer.getInt("MAX(orderID)");
                
                transfer = dbc.executeQuery(getCart);
                String orderTransfer;
                int itemId, qty;
                while(transfer.next()){
                    itemId = transfer.getInt("itemID");
                    qty = transfer.getInt("quantity");
                    orderTransfer = "INSERT INTO order_details(orderID, itemID, qty) VALUES ('"+ orderID +"', '"+itemId+"', '"+qty+"')";
                    dbc.updateQuery(orderTransfer);
                }
                
                String getCartIds = "SELECT cartID FROM accountcart WHERE accountID = '" + cpl.getMfl().getAccount().getUserId() + "'";
                ResultSet rs = dbc.executeQuery(getCartIds);
                int removeId;
                while(rs.next()){
                    removeId = rs.getInt("cartID");
                    cpl.remove("accountcart", "cartID = '"+ removeId +"'");
                    cpl.remove("cart", "cartID = '" + removeId + "'");
                }
                
                }catch(Exception e){
                e.printStackTrace();
            }
            cpl.getMfl().getMainFrame().getCenterPanel().getCartPanel().refreshCart();
            
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_returnBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JComboBox<String> shipAddressbox;
    private javax.swing.JComboBox<String> shipMethodBox;
    // End of variables declaration//GEN-END:variables
}
