/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.MainFrame_Listener;
import java.sql.ResultSet;
import java.util.ArrayList;
import model.DBConnection;

/**
 *
 * @author amiel
 */
public class ResultFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResultFrame
     */
    private String search;
    private DBConnection dbc;
    private MainFrame_Listener mfl;
    private String[][] values;
    public ResultFrame(MainFrame_Listener mfl) {
        dbc = new DBConnection();
        dbc.getConnection();
        search = "company";
        this.mfl = mfl;
        addTableValue();
        initComponents();
        setVisible(true);
    }
    private void addTableValue(){
        ArrayList<String> companies = new ArrayList<>();
        try{
            ResultSet rs = dbc.executeQuery("SELECT " + search + "Name FROM " + search + " ORDER BY " + search + "ID");
            String profitResult;
            while(rs.next()){
                companies.add(rs.getString(search + "Name"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        String[][] values = new String[companies.size()][13];
        
        for(int i = 0 ; i < companies.size() ; i ++){
            for(int j = 0 ; j < 13 ; j++){
                values[i][j] = "0";
            }
        }
        for(int i = 0 ; i < companies.size() ; i ++){
            values[i][0] = companies.get(i);
            addValues(values, i);
        }
        this.values = values;
        
    }
    public void refreshTable(){
        addTableValue();
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            values,
            new String [] {
                search, "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"
    }
));
    }
    private void addValues(String[][] val, int cId){
        int year;
        try{
            year = (Integer) yearSpinner.getModel().getValue(); 
        }catch(Exception e){
            year = 2017;
        }
        
        try{
            String profitResult = "SELECT MONTH(o.orderdate) as 'month', SUM(itemPrice) as 'total'\n" +
                                    "FROM order_details od, "+ search +" c, `order` o, items i\n" +
                                    "WHERE od.orderid = o.orderid AND\n" +
                                    "	od.itemID = i.itemID AND\n" +
                                    "    i." + search + "ID = c." + search + "ID AND\n" +
                                    "    YEAR(o.orderdate) = '"+ year +"' AND\n" +
                                    "    c." + search + "ID = '" + (cId + 1) + "' " +
                                    "GROUP BY MONTH(o.orderdate)";
            ResultSet rs = dbc.executeQuery(profitResult);
            int index;
            String value;
            while(rs.next()){
                index = rs.getInt("month");
                value = rs.getString("total");
                val[cId][index] = value;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        returnBtn = new javax.swing.JButton();
        yearSpinner = new javax.swing.JSpinner();
        refreshBtn = new javax.swing.JButton();
        optionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(204, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            values,
            new String [] {
                "Company", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        yearSpinner.setModel(new javax.swing.SpinnerNumberModel(2017, null, null, 1));

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        optionBtn.setText("Categories");
        optionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBtn)
                .addGap(38, 38, 38)
                .addComponent(optionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshBtn)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBtn)
                    .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn)
                    .addComponent(optionBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        mfl.getMainFrame().setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_returnBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        refreshTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void optionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBtnActionPerformed
        if(optionBtn.getText().compareToIgnoreCase("Categories") == 0){
            search = "category";
            optionBtn.setText("Companies");
        }else{
            search = "company";
            optionBtn.setText("Categories");
        }
        refreshTable();
    }//GEN-LAST:event_optionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton optionBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
